export const FormActionsType = {

  // STATES
  UPDATE_FORM_USER_DATAS: "UPDATE_USER_DATAS",
  SET_EDITING_USER_ID: "SET_USER_ID",
  SET_FORM_ERROR: "SET_FORM_ERROR",
  
  RESET_FORM_DATAS: "RESET_FORM_DATAS",
  
  // SAGA
  SAGA_HANDLE_FORM_INPUT_CHANGES: "SAGA_HANDLE_FORM_INPUT_CHANGES",
  SAGA_HANDLE_SUBMIT_NEW_FORM: "SAGA_HANDLE_SUBMIT_NEW_FORM",
  SAGA_HANDLE_SUBMIT_EDIT_FORM: "SAGA_HANDLE_SUBMIT_EDIT_FORM",
  SAGA_SET_EDITING_USER_ID: "SAGA_SET_USER_ID",
};
