
export const USER_INITIAL_STATE = {
    name: {value:""},
    internalNotes: {value:""},
    email: {value:""},
    rg: {value:""},
    cpf: {value:""},
    age: {value:""},
    birth: {value:""},
    phone: {value:""},
    street: {value:""},
    number: {value:""},
    complement: {value:""},
    neighborhood: {value:""},
    city: {value:""},
    state: {value:""},
    education: {value:""},
    course: {value:""},
    whatsAppGroup: {value:""},
    whatsAppInfos: {value:""},
    alergies: {value:""},
    medicines: {value:""},
    emergencyContact: {value:""},
    bloodType: {value:""},
    smoke: {value:""},
    drink: {value:""},
    exercises: {value:""},
    professional: {value:""},
    eventsXP: {value:""},
    shirt: {value:""},
    pants: {value:""},
    shoes: {value:""},
    area: {value:""},
    position: {value:""},
    memberSince: {value:""},
    active: {value:""},
    permission: {value:""},
    declaration: {value:""},
    updatedDate: {value: ""},
  };
  