export const EventsActionsType = {
  //STATES
  SET_ALL_EVENTS: "SET_ALL_EVENTS",
  SET_EVENTS_YEARS: "SET_EVENTS_YEARS",
  SET_EVENT_FORM_DATAS: "SET_EVENT_FORM_DATAS",
  SET_EVENT_FORM_IMAGE_URL: "SET_EVENT_FORM_IMAGE_URL",
  SET_EVENT_ATTENDEES_IDS: "SET_EVENT_ATTENDEES_IDS",
  SET_IS_EDITING_ATTENDEES: "SET_IS_EDITING_ATTENDEES",
  SET_EVENTS_ERROR: "SET_EVENTS_ERROR", 

  //SAGA
  // events page
  SAGA_GET_EVENTS_FROM_FIRESTORE: "SAGA_GET_EVENTS_FROM_FIRESTORE",
  SAGA_HANDLE_EVENTS_FROM_FIRESTORE: "SAGA_HANDLE_EVENTS_FROM_FIRESTORE",
  SAGA_GET_EVENTS_BY_YEAR: "SAGA_GET_EVENTS_BY_YEAR",
  
  // event page
  SAGA_DELETE_EVENT: "SAGA_DELETE_EVENT",
  SAGA_DELETE_EVENT_FROM_CARD: "SAGA_DELETE_EVENT_FROM_CARD",
  SAGA_UPLOAD_EVENT_ON_FIRESTORE: "SAGA_UPLOAD_EVENT_ON_FIRESTORE",
  SAGA_UPDATE_EVENT_ON_FIRESTORE: "SAGA_UPDATE_EVENT_ON_FIRESTORE",
  
  // event form
  SAGA_HANDLE_EVENT_FORM_CHANGE: "SAGA_HANDLE_EVENT_FORM_CHANGE",
  SAGA_GET_EVENT_FORM_DATAS: "SAGA_GET_EVENT_FORM_DATAS",
  SAGA_RESET_EVENT_FORM: "SAGA_RESET_EVENT_FORM",
  
  // event image
  SAGA_UPLOAD_IMG: "SAGA_UPLOAD_IMG",
  SAGA_GET_IMG_URL: "SAGA_GET_IMG_URL",
  
  // event attendees
  SAGA_HANDLE_SAVE_ATTENDEES: "SAGA_HANDLE_SAVE_ATTENDEES",
  SAGA_DELETE_ATTENDEE: "SAGA_DELETE_ATTENDEE", 


};
