export const SearchBarActionsTypes = {

    // STATE
    SET_SEARCH_TERM: "SET_SEARCH_TERM",
    SET_SEARCHED_RESULTS: "SET_SEARCHED_RESULTS",
    SET_SHOW_SUGGESTIONS: "SET_SHOW_SUGGESTIONS",
    SET_SEARCH_BAR_ERROR: "SET_SEARCH_BAR_ERROR",

    // SAGA
    SAGA_FILTER_USERS: "SAGA_FILTER_USERS"
}
