export const TableActionsType = {

  //STATES
  //arrays
  SET_USERS_TABLE_ARRAY: "SET_USERS_TABLE_ARRAY",
  SET_USERS_SEARCH_ARRAY: "SET_USERS_SEARCH_ARRAY",
  SET_USERS_APPROVED_ARRAY: "SET_USERS_APPROVED_ARRAY",
  SET_USERS_PENDING_ARRAY: "SET_USERS_PENDING_ARRAY", 
  SET_USERS_DISPLAY_ARRAY: "SET_USERS_DISPLAY_ARRAY",
  
  SET_IS_APPROVED_TAB_SHOW: "SET_IS_APPROVED_TAB_SHOW",
  SET_IS_APPROVED_TAB_ACTIVE_USERS: "SET_IS_APPROVED_TAB_ACTIVE_USERS",
  SET_TABLE_COLUMNS: "SET_TABLE_COLUMNS",
  SET_TABLE_ERROR: "SET_TABLE_ERROR",
  
  //SAGA
  SAGA_SET_IS_APPROVED_TAB_SHOW: "SAGA_SET_IS_APPROVED_TAB_SHOW",
  SAGA_SORT_COLUMNS: "SAGA_SORT_COLUMNS",
  SAGA_GET_USERS_FROM_DB: "SAGA_GET_USERS_FROM_DB",
  SAGA_SET_ARRAYS: "SAGA_SET_ARRAYS",

  

};
