export const CurrenUserActionsTypes = {
    // STATE
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_AUTH_ERROR: "SET_AUTH_ERROR",
    SET_PERSISTENCE: "SET_PERSISTENCE",
    
    // REDUCER
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",

    // SAGA
    SAGA_SET_USER_AUTH: "SAGA_SET_USER_AUTH",
    SAGA_SIGN_OUT: "SAGA_SIGN_OUT",
    SAGA_EMAIL_SIGN_IN: "SAGA_EMAIL_SIGN_IN",
    SAGA_EMAIL_SIGN_UP: "SAGA_EMAIL_SIGN_UP",
}
